import React from "react";
import "../../style/components/SchematicDescription.css";

/**
 * The schematic description component.
 */
const SchematicDescription = () => (    
    <div id="schematic-description">
        <p>
            This block diagram shows the important elements of a FTMW spectrometer; 
            please tap on them to learn more! The electronic sequence begins with a 
            continuous-wave signal from the MW synthesizer <b>(1)</b> being split by a power 
            divider <b>(2)</b>. The remaining processing can be separated into a broadcasting 
            arm <span style={{color: "green"}}>(green)</span> and receiving arm <span style={{color: "purple"}}>(purple)</span>. 
            The broadcasting arm operates as follows: A 30 MHz radio frequency (RF) reference signal is generated by <b>(3) </b> 
            and mixed with the MW signal using a single sideband mixer <b>(4)</b>. This results 
            in a signal that has a frequency that is the sum of the two, which is referred 
            to as the tuning frequency. It then passes through a power amplifier <b>(5)</b> and 
            a MW switch <b>(6)</b>, which gates the pulse to the circulator <b>(7)</b>, directing it 
            into the wire hook antenna <b>(8)</b> that couples the radiation into the Fabry-Pérot 
            cavity <b>(9)</b>. Inside the cavity, the MW field interacts with a molecular pulse 
            introduced via a solenoid valve <b>(10)</b> that is controlled by a power supply 
            driver <b>(11)</b>. The free induction decay (FID) signal is received by the antenna 
            <b>(8)</b> and directed via the circulator <b>(7)</b> to the receiving arm: Here, the signal 
            is gated <b>(12)</b> to a low-noise amplifier <b>(13)</b> and then heterodyned through an 
            image rejection mixer <b>(14)</b>. This results in a signal that is the sum of the 
            reference signal (30 MHz) and the difference frequency between the molecular 
            signal and the tuning frequency. The gain is increased as this RF signal passes 
            through an amplifier <b>(15)</b> before digitization with an oscilloscope <b>(16)</b>. 
            Synchronization is provided by a 10 MHz frequency reference <b>(17)</b>, with precise 
            timing controlled by a pulse generator <b>(18)</b>. For an animation of how the spectrometer 
            works please tap on the cavity.
        </p>
    </div>
)

export default SchematicDescription;